name: Build Kernel Packages

on:
  push:
    tags:
      - "paf-kernel-*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_BRANCH: linux-5.12.y
      DTC_FLAGS: -@
      ARCH: arm
      CROSS_COMPILE: arm-linux-gnueabihf-
    steps:
      - name: Checkout upstream
        uses: actions/checkout@v2
        with:
          repository: gregkh/linux
          ref: ${{ env.UPSTREAM_BRANCH }}
          path: linux
      - name: Checkout configuration
        uses: actions/checkout@v2
      - name: Overwrite configuration
        run: cp ./sunxi_defconfig ./linux/arch/arm/configs/sunxi_defconfig
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y flex bison build-essential gcc-arm-linux-gnueabihf
          
      - name: Configure build
        working-directory: ./linux
        run: make sunxi_defconfig
      - name: Build
        working-directory: ./linux
        run: make bindeb-pkg
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux-image*.deb
            linux-headers*.deb
            linux-libc*.deb
